DEVEXP-527: Starting on tests for cascading collections and permissions.
marklogic/ml-javaclient-util pull request #186
Opened 2023-08-22 16:04 UTC by BillFarber

Is this what you're thinking for the tests?

Note the "setCascadeCollections" method I added. I don't know if I'm going the right direction for that. I just needed something to make the test.

2023-08-24 15:51 UTC, BillFarber commented
The new version of this PR is intended simply to share an initial implementation strategy and to discuss it's pros and cons.

2023-08-24 19:29 UTC, rjrudin requested changes
Looks good, just a couple test changes.

2023-08-24 19:29 UTC, rjrudin commented on src/test/java/com/marklogic/client/ext/file/CascadeCollectionsAndPermissionsFileProcessorTest.java
Just do "CascadeCollectionsAndPermissionsTest" so the test class name is about the use case as opposed to the classes involved. The existing tests for collections/permissions unfortunately follow the "(class name)Test" pattern - I try to only use that for pure unit tests that focus on several methods of a test. Ignore my lousy naming with those classes, "(Use case)Test" is the way to go.

2023-08-24 19:29 UTC, rjrudin commented on src/test/java/com/marklogic/client/ext/file/CascadeCollectionsAndPermissionsFileProcessorTest.java
> +	public void ChildHasSettingsUsedWhenParentHasNoSettings() {
Still do lowerCamel for these test names, just like the first one.

2023-08-24 19:29 UTC, rjrudin commented on src/test/java/com/marklogic/client/ext/file/CascadeCollectionsAndPermissionsFileProcessorTest.java
> +		Optional<DocumentFile> optionalTestFile = files.stream().filter(file -> "/child1_1-noCP/test.json".equals(file.getUri())).findFirst();
It's okay to test the DocumentFile objects that are returned, but what we really care about is that the modules were loaded correctly - users care about that, ml-gradle users will never see the List. Use the `verifyCollections` and `verifyPermissions` methods I added - they'll make the test much shorter and easier to read. If you want, include assertions on the List that's returned as well, though we can safely assume that if the modules were loaded correctly, then the List is going to be correct as well (I would not bother with those assertions).

2023-08-25 13:49 UTC, rjrudin requested changes
Looks good, just one tiny change and then merge away.

2023-08-25 13:49 UTC, rjrudin commented on src/main/java/com/marklogic/client/ext/file/CascadingPropertiesDrivenDocumentFileProcessor.java
> +public abstract class CascadingPropertiesDrivenDocumentFileProcessor extends PropertiesDrivenDocumentFileProcessor {
Remove "public" here - another mistake I made was making everything public initially.

2023-08-25 13:55 UTC, merged